version: '3.7'
services:
    web:
        image: nginx
        ports:
            - '80:80'
        volumes:
            - './pub:/var/www/html'
            - './default.conf:/etc/nginx/conf.d/default.conf'
            - './.htpasswd:/etc/nginx/.htpasswd'
